import streamlit as st
import re
from openai import OpenAI
import openai
import uuid
from supabase import create_client, Client 
from datetime import datetime

# --- 1. PAGE SETUP & STATE INITIALIZATION ---

st.set_page_config(page_title="Counterpoint", layout="wide")
st.title(" AI Keyword Generator Workspace")

# --- CLOUD DATABASE SETUP ---
try:
    # Grab the keys from Streamlit secrets
    supabase_url = st.secrets["connections"]["supabase"]["SUPABASE_URL"]
    supabase_key = st.secrets["connections"]["supabase"]["SUPABASE_KEY"]
    supabase: Client = create_client(supabase_url, supabase_key)
except Exception as e:
    st.error(f" Database connection failed: {e}")
    st.stop()

# Assign this specific user a unique session ID so their data doesn't mix with others
if "session_id" not in st.session_state:
    current_time = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    st.session_state.session_id = f"{current_time}_{str(uuid.uuid4())}"

if "saved_topic" not in st.session_state:
    st.session_state.saved_topic = "The United States Federal Government should enact a policy to establish a comprehensive, high-speed rail network in the USA."

current_topic_input = st.session_state.saved_topic
# Initialize Session State to hold our generated keywords so they don't disappear
if "final_keywords" not in st.session_state:
    st.session_state.final_keywords = []

# --- 2. SIDEBAR: CONFIGURATION & PROMPTS ---
with st.sidebar:
    st.header(" Generation Settings")
    
    
    num_sub_categories = st.slider("Number of Sub-Niches", min_value=1, max_value=10, value=6)
    num_keywords_per_niche = st.slider("Keywords per Niche", min_value=1, max_value=10, value=5)

    st.divider()
    
    # EXPANDER 1: SYSTEM PROMPTS
    
    with st.expander("Advanced: Edit System Prompts"):
        niche_system = st.text_area(
            "Sub-Niche System Prompt", 
            value="""You are an expert academic researcher. \nYour ONLY job is to output a list. Provide ZERO conversational filler. DO NOT say "Here are the categories".""",
            height=100
        )
        
        keyword_system = st.text_area(
            "Keyword System Prompt",
            value="""You are an expert academic researcher. \nYour ONLY job is to output a single, highly optimized search query for academic databases based on the user's topic.\nProvide ZERO conversational filler.""",
            height=120
        )
    user_api_key = st.text_input("Groq API Key:", type="password") # alow the user to put in there own API keys

        


    # EXPANDER 2: USER PROMPTS
    #MOST IMPORTANT EXPANDER this creates a template for how the AI generates keyowrds
    #uses many dynamic variables and makes it a template so the prompt can be cahnged here then the varibles cna be added later in funtions
    # the TOPIC varible is changed at the top of the page and set by the user the num_specific catagories is set by the slider refrenced above
    with st.expander("Advanced: Edit User Prompts"):
        st.caption("⚠️ Keep the curly brace placeholders like {topic} or {sub_niche} intact so the app can insert your settings variables dynamically.")
        
        niche_user_template = st.text_area(
            "Sub-Niche User Prompt Template",
            value="""Generate EXACTLY {num_sub_categories} highly specific sub-categories of this topic: "{topic}".

Zero Context. Return ONLY a list with each sub-category on a new line. Do not use commas or bullet points.

MOST IMPORTANT RULE: Make sure someone could read your sub-categories and immediately identify that they are specifically about "{topic}". 

Good Sub-Categories Example:
Specific, self-contained sub-topics that explicitly mention "{topic}" or its core components (e.g., "Economic Feasibility and Capital Costs of {topic} Deployment" or "Regulatory Challenges and Licensing Frameworks for {topic}").

Bad Sub-Categories Example:
'Economic development', 'Infrastructure funding', 'Policy frameworks'. (These are too broad and not easily recognizable as specifically belonging to {topic}).

Extra Rule: Do NOT use ambiguous or confusing acronyms. Always spell out full technical terms.

YOU MUST MAKE SURE YOUR RESPONSES ARE DIRECTLY AND CLEARLY RELATED TO: "{topic}".""",
            height=300
        )
        #this is where the keywords ar directly generated nums per niche is set by the user on the slider and the subnich is generated by the previouse pormpy
        # the dynamic example is to get around an AI quirk. LLama 3.1 is more of a "visual learner" so based on the number of keywords the number of examples in the dynamic example changes and so you accutually get how many keyowrds you want
        keyword_user_template = st.text_area(
            "Keyword User Prompt Template",
            value="""Content Focus: Generate EXACTLY {num_keywords_per_niche} concise, highly specific search phrases related to this sub-niche: "{sub_niche}".

Zero Context Policy: Provide ONLY the keywords. Do not include any introductory text, numbers, or conversational filler. 

MOST IMPORTANT RULE: Do NOT repeat the full sub-niche name in your output. These need to be short, punchy queries designed to be typed into academic databases like JSTOR or Google Scholar (3 to 15 words maximum).

Examples of good keywords:
'economic feasibility high-speed rail', 'regulatory policy impact transit', 'empirical cost-benefit analysis rail', 'deployment timeline regression'.

Examples of bad keywords:
'Regional economic growth indicators', 'Investment impact assessment', 'Policy framework analysis'. (These are too broad).

Formatting: Output your response matching the exact number of lines in this template below. Do not include extra lines.

Template to follow:
{dynamic_example}

YOUR RESPONSE MUST CONTAIN EXACTLY {num_keywords_per_niche} LINES FOR THE TOPIC: {sub_niche}""",
            height=350
        )
# --- 3. MAIN UI: TOPIC & CUSTOM INPUTS ---
#MOST IMPORTANT DROPDOWN. this allows users to cahnge the topic of the debate making this tool actually usful. maybe.
# Streamlit will automatically grab the default from st.session_state.topic, 
# and automatically save any changes the user types back into it!
current_topic_input = st.text_input(
    " Main Topic or Resolution. Make sure to click enter to save.", 
    value=st.session_state.saved_topic
)

st.session_state.saved_topic = current_topic_input
# DELETE THIS LINE entirely:
# st.session_state.topic = topic

# Use columns to put the custom input boxes side-by-side to save space
# colums set up so the user can put in sub niches and keywords they really wnat
col1, col2 = st.columns(2)
# so by addign subniches you can set a geral catagory and keywords allow the user to focus on specific things 
# this makes the tool much more usable and not entirly relant on a ... unreliable llama 3.1
with col1:
    manual_niches = st.text_area(
        "Add Custom Sub-Niches (Optional)", 
        placeholder="Eminent domain issues\nHigh-speed rail environmental benefits\n(Type each on a new line)",
        height=120
    )

with col2:
    manual_input = st.text_area(
        "Add Custom Keywords (Optional)", 
        placeholder="Specific author name 2024\nExact phrase search\n(Type each on a new line)",
        height=120
    )
# this is where it all comes together when this button is clicked all the varibles built up above will come into placy
# --- 4. GENERATION ENGINE ---
if st.button(" Generate AI Keywords", type="primary"):
    if not user_api_key:
        st.error(" you dont have a API key! Go get one!")
        st.stop()

    # Grab manual inputs
    # i know this line cleans up custome keywords but now sure how I KNOW NOW first it take ever single custom keyword and for each it removes 
    #unwanted spaces with k.strip() then it splits it by newlines so each custome keyword is its own this manual_input.split('\n') then it checks and removes emprty ones with k.strip()
    custom_keywords = [k.strip() for k in manual_input.split('\n') if k.strip()]
    # this though i get it makes a temp keyword list with all the custom keyword in it so the script can add them on top of the AI ones later
    temp_keyword_list = custom_keywords.copy()
    #still know it cleans custom niches but not sure now I KNOW NOW SAME AS ABOVE
    custom_niches = [n.strip() for n in manual_niches.split('\n') if n.strip()]
    #this calls ollama and establishes as the local model provider i think
    client = OpenAI(api_key=user_api_key, base_url="https://api.groq.com/openai/v1")
    MODEL = "openai/gpt-oss-20b"
    #dont know what a spinner is
    #  i do know that here is where the template from above gets filled in with valibles this is when the topic is put in and the num of sub catogories
    #I KNOW NOW format fills the empty variables
    with st.spinner("Generating AI sub-niches..."):
        #.format is confusing though what does that do?
        niche_prompt = niche_user_template.format(
            num_sub_categories=num_sub_categories, 
            topic=current_topic_input
        )

        try:
            #sends a chat to ollama telling it to use llama 3.1 to resoind setting the ststem to what was above to explaint to llama what to do and sending a "user" for llama to reaspond to that is our formatted prompt form aboce to get niches
            niche_response = client.chat.completions.create(
                model=MODEL, 
                messages=[
                    {"role": "system", "content": niche_system},
                    {"role": "user", "content": niche_prompt}
                ]
            )
            #takes the reasponse from llama prosses it by removing AI tendancy to use bullet points and number in list  then takes the first num of sub nihces from it to avoif the AI over generating
            ai_niche_text = niche_response.choices[0].message.content.strip()
            ai_sub_niches = [line.replace("- ", "").replace("* ", "").strip() for line in ai_niche_text.split('\n') if line.strip()]
            ai_sub_niches = ai_sub_niches[:num_sub_categories]
            #if it doesnt work print an execption and stop for stom reason? maybe it stops to stop the code below from running because it might because of streamlit or smt
        
        except openai.RateLimitError as e:
            error_str = str(e)
            # Extract the "try again in X" message using regex
            match = re.search(r"try again in\s+([^.]+)", error_str, re.IGNORECASE)
            wait_info = f"\n\n⏱️ **Time until reset / retry:** `{match.group(1).strip()}`" if match else ""
            
            st.error(f"⚠️ **Daily Token Limit Reached!**\n\nYour Groq API key has used up its free quota.{wait_info}\n\nPlease wait for the reset, or switch to a new API key in the sidebar.")
            st.stop()  # Notice the () function call!
                    
        except Exception as e:
            st.error(f"API Connection Error: {e}")
            st.stop()

    # Combine the AI generated niches with your custom ones
    # pretty simple combines all the niches int o one big list and notifies the user
    all_sub_niches = ai_sub_niches + custom_niches
    st.success(f"Combined {len(ai_sub_niches)} AI Niches and {len(custom_niches)} Custom Niches!")

    progress_bar = st.progress(0)
    #this sets up a progress bar to udate the user on how many keywords have been generated
    
    # Loop through ALL niches (AI + Custom)
    #makes a loop to repeat keyword generat based on num of sub niches
    for i, sub_niche in enumerate(all_sub_niches):
        with st.spinner(f"Generating keywords for: {sub_niche}..."):
            #sets the dynamic example heres how i think jsut a guess. firs \n.join puts a newline at the front of every examples
            #second f"keyword{j+1} sets a valible j to go after keyword this will look like keyword 1 keyword 2 ect
            # finally j is use in range (num key words) and so based on the length of num_keywords_per_niche thats how many formated examples there will be
            dynamic_example = "\n".join([f"keyword {j+1}" for j in range(num_keywords_per_niche)])

            #this is setting the template for the keyword prompt and filling all the previously empty variables
            keyword_prompt = keyword_user_template.format(
                num_keywords_per_niche=num_keywords_per_niche,
                sub_niche=sub_niche,
                dynamic_example=dynamic_example
            )
            # this is jsut like above sending a chat to ollama with llama3 and thge prompts from above to get the kkeword this will be repeat relitive to number of niches
            # Wrap this call in a try/except just like the first one!
            try:
                response = client.chat.completions.create(
                    model=MODEL,
                    messages=[
                        {"role": "system", "content": keyword_system},
                        {"role": "user", "content": keyword_prompt} 
                    ]
                )
            except openai.RateLimitError as e:
                st.error("⚠️ **Daily Token Limit Reached!** You ran out of tokens while generating keywords. Please wait for the daily reset or use a new API key.")
                st.stop() # Safely halts the script right here
            except Exception as e:
                st.error(f"API Connection Error during keyword generation: {e}")
                st.stop()
            #takes jsut the message part of the reaspons form ollam this is the keywrod part we want
            #it strips it to remove spaces(feel free to add on)
            ai_text = response.choices[0].message.content.strip()
            #huh i know it cleans but why and how? I KNOW NOW it removes extra space then splits them by newline so they become a list where each is a keyowrd then removes emptys
            clean_lines = [line.strip() for line in ai_text.split('\n') if line.strip()]
            #only takes the first num_keywords_per_niche so even if llama overshoots we good
            final_lines = clean_lines[:num_keywords_per_niche]
            
            for line in final_lines:
                #now the keword list with the custom keywords is appended with all the AI keywords!
                #dont know how the cleaning happend though this removes numbers and bullet points

                cleaned_line = line.replace("- ", "").replace("* ", "").strip()
                cleaned_line = re.sub(r'^\d+\.\s*', '', cleaned_line)
                temp_keyword_list.append(cleaned_line)
                
        # Update progress bar based on the total number of combined niches
        #now that we have itterated we update the progress bar for the user!
        progress_bar.progress((i + 1) / len(all_sub_niches))
    #safley stores the keywords in session state!   
    st.session_state.final_keywords = temp_keyword_list
    
    with st.spinner(" Saving keywords to your cloud database..."):
        # First, delete any old keywords from this user's session so we don't get duplicates
        supabase.table("user_keywords").delete().eq("session_id", st.session_state.session_id).execute()
        
        # Now, insert the fresh batch of keywords one by one
        for kw in temp_keyword_list:
            supabase.table("user_keywords").insert({
                "keyword": kw,
                "session_id": st.session_state.session_id
            }).execute()
            
    st.success(" Generation Complete and saved to the cloud!")

# --- 5. RESULTS & EXPORT ---
# if final kerods exist now great a formatedlist of all the keywords for the user to see
if st.session_state.final_keywords:
    st.divider()
    #tells the total
    st.subheader(f" Final Keyword List ({len(st.session_state.final_keywords)} total)")
    
    formatted_list = "\n".join(st.session_state.final_keywords)
    #this is how its desplayed but it is unfaliar systax to me
    st.code(formatted_list, language="text")
    #dowload button! when clicked it mimes or somthing? I know it puts it in test key but what is mime? MIME explaines to the computer hwo to dowload!
    st.download_button(
        label=" Download Keywords as TXT",
        data=formatted_list,
        file_name="test_key.txt",
        mime="text/plain"
    )
    if st.button(" Clear Workspace", type="primary"):
        st.session_state.final_keywords = []
        st.rerun()
         

    